### ISSUE TITLE
Gain more permissions for the Community-Team 

### ISSUE THREAD

**Issue by leogopal** [WordPress/Community#1]
I would like to have a bit more privileges to adjust things like the team description, icon, ability to create smaller repos, and have teams within the main team that are dedicated to various projects so we might manage and communicate with them easier and better.

Can you help me attain that purely for this team @dd32

**Comment by dd32** [comment]
Unfortunately GitHub permissions are not as granular as you may want.

For now, if you can't do something, just post a request here mentioning me, or post in #meta.

I believe you may run into problems with new Project boards being private by default, and needing to request a GitHub admin change it's visibility to public.
It also looks like you've had some issues with teams, that sends the GitHub admins an email asking for confirmation of the change - but either the request was canceled or GitHubs got a UI bug as it didn't show the request.

I've removed the `community-team` in favour of the `make-community-team` because I thought that was what you were trying to do, but I'm not sure that was the case :) You should be able to create child teams here: https://github.com/orgs/WordPress/teams/make-community-team/teams - if not, let me know what you need created and I'll do so.
