### ISSUE TITLE
[Meetup]: Dubai, UAE

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Community#89]
### Meetup City or Event Name

[Meetup]: Dubai, UAE

### Meetup Tracker Link

https://central.wordcamp.org/wp-admin/post.php?post=5655400&action=edit

### Meetup HelpScout Link

https://secure.helpscout.net/conversation/2522826762/173819/

**Comment by flopez1977** [comment]
Conclusions: 16/3/2024

Go for orientation, the current meetupo group is withouc activity and is not an official one. It would be great if she can contact them to try to contact 388 people involved in the group.

-> HelpScout link: https://secure.helpscout.net/conversation/2522826762/173819/
-> Conclusion:
Tracker:
HELP SCOUT
organizer name Menaka S
organizer email address [menakas@yahoo.com](mailto:menakas@yahoo.com)
group location Dubai
event location Dubai
SEARCHES
WordPress Meetup + LOCATION =
https://www.meetup.com/dubai-wordpress-meetup/ there is a an unofficial meetup group. This group was created on 2014 and there was some events , the group stopped and began again on 2020 and there was some events. The last event it was on Oct 2020.
Make sure the location is a city, not a region.
ORGANIZER + WordPress all is about his enterprise and WordUp
ONLINE PRESENCE
Twitter https://twitter.com/smenaka?lang=en
Facebook
LinkedIn
.org profile https://profiles.wordpress.org/menakas since 2013 and is a core contributor, translation editor, plugin developer, WC Speaker and works in automattic.
GitHub profile
personal site
business site
GPL no flags No Red Flags
Trademark violations. No WP Violations
check for WP activity on Meetup.com

**Comment by flopez1977** [comment]
Closing ticket
